added new functional
JaysonJuza/online-book-store-app pull request #1
Opened 2024-04-04 11:00 UTC by JaysonJuza

created a Spring Boot project with pom.xml file with all required dependencies
added Book entity
added BookRepository
added BookService
customized database access
customizedcheckstyle
customized application.properties in the test/resources folder
customized CI (Continuous Integration)

2024-04-04 11:52 UTC, MAMentorFX requested changes

2024-04-04 11:52 UTC, MAMentorFX commented on mvnw
> +#!/bin/sh
mvnw and mvnw.cmd should  be in gitignore file

2024-04-04 11:52 UTC, MAMentorFX commented on src/main/java/onlinebookstoreapp/model/Book.java
> +@Data
Forget abuut @Data for entities, @Data consists of @EqualsAndHashCode and @ToString, those two may lead to Lazy loading exception. Use @Getter and @Setter instead

2024-04-04 11:52 UTC, MAMentorFX commented on src/main/java/onlinebookstoreapp/model/Book.java
> +    private BigDecimal isbn;
shoudl be unique

2024-04-05 18:06 UTC, MAMentorFX requested changes
Put mvn related files to gitignore

2024-04-05 18:06 UTC, MAMentorFX commented on mvnw
> +#!/bin/sh
Not fixed.
Also .mvn/wrapper in gitignore.

2024-04-05 18:06 UTC, MAMentorFX commented on src/main/java/onlinebookstoreapp/model/Book.java
> +    private BigDecimal isbn;
fixed

2024-04-06 10:29 UTC, MentorMA requested changes
resolve problem with git ignore files, clear redundant files from repository

2024-04-07 10:11 UTC, MAMentorFX approved these changes

2024-04-09 09:13 UTC, merged